name: anti-viral-protocol # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: shooter, Side scroller, platformer, game # 79 char long summary
description: |
  This is Anti-Viral Protocol, a side-scroller platformer but with guns. In this game the player is tasked to shootdown viruses across levels to defeat the boss and obtain the Vaccine to destroy all the remaining viruses around the world.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  anti-viral-protocol:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    python-packages:
      - pygame
    source: https://github.com/RishiMenon2004/Anti-Viral-Protocol.git
    
apps:
    anti-viral-protocol:
        command: bin/run.py
